/**
 * TypeScript service wrapping Rust browser engine via WASM
 * Provides minimal memory footprint by offloading to Rust
 */

// Import WASM module (generated by wasm-pack)
// @ts-ignore - WASM module will be generated at build time
// import init, { WasmBrowser } from '../../pkg/rust_browser.js';

// Placeholder until WASM is built
const init = async () => {};
class WasmBrowserPlaceholder {
  constructor(_engineType: string) {}
  create_tab(_url: string | null) { return `tab-${Date.now()}`; }
  close_tab(_tabId: string) {}
  async navigate(_tabId: string, _url: string) {}
  active_tab() { return null; }
  get_tab_info(_tabId: string) { return null; }
}
const WasmBrowser = WasmBrowserPlaceholder;

let wasmInitialized = false;
let wasmBrowser: WasmBrowser | null = null;

export class RustBrowserService {
  private static instance: RustBrowserService | null = null;

  private constructor() {}

  static async getInstance(engineType: 'servo' | 'webkit' = 'servo'): Promise<RustBrowserService> {
    if (!wasmInitialized) {
      await init();
      wasmInitialized = true;
    }

    if (!wasmBrowser) {
      wasmBrowser = new WasmBrowser(engineType);
    }

    if (!this.instance) {
      this.instance = new RustBrowserService();
    }

    return this.instance;
  }

  async createTab(url?: string): Promise<string> {
    if (!wasmBrowser) {
      throw new Error('WASM browser not initialized');
    }
    return wasmBrowser.create_tab(url || null);
  }

  async closeTab(tabId: string): Promise<void> {
    if (!wasmBrowser) {
      throw new Error('WASM browser not initialized');
    }
    wasmBrowser.close_tab(tabId);
  }

  async navigate(tabId: string, url: string): Promise<void> {
    if (!wasmBrowser) {
      throw new Error('WASM browser not initialized');
    }
    await wasmBrowser.navigate(tabId, url);
  }

  getActiveTab(): string | null {
    if (!wasmBrowser) {
      return null;
    }
    return wasmBrowser.active_tab() || null;
  }

  getTabInfo(tabId: string): any {
    if (!wasmBrowser) {
      return null;
    }
    return wasmBrowser.get_tab_info(tabId);
  }
}

